apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-eventstore-{{.Values.sales.name}}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: external-tcp-port
      port: {{.Values.sales.eventStore.externalHttpPort}}
      targetPort: {{.Values.sales.eventStore.externalHttpPort}}
    - name: http-port
      port: {{.Values.sales.eventStore.httpPort}}
      targetPort: {{.Values.sales.eventStore.httpPort}}
  selector:
    app: eventstore-{{.Values.sales.name}}
