apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  name: {{.Release.Name}}-{{.Values.sales.name }}
  labels:
    app: {{.Values.sales.name }}
spec:
  replicas: {{.Values.sales.replicas }}
  template:
    metadata:
      name: {{.Values.sales.name }}
      labels:
        app: {{.Values.sales.name }}
    spec:
      containers:
        - name: app-container
          image: {{ .Values.sales.image }}
          imagePullPolicy: {{ .Values.sales.imagePullPolicy }}
          env:
            - name: BrewUp__EventStoreSettings__ConnectionString
              value: 'ConnectTo=tcp://brewup-micro-eventstore-{{.Values.sales.name }}.{{ .Values.global.namespaceOverride | default .Release.Namespace }}.svc.cluster.local:{{.Values.sales.eventStore.externalHttpPort }};UseSslConnection=false'
            - name: BrewUp__MongoDbSettings__ConnectionString
              value: 'mongodb://root:t00rM3Pswd@brewup-micro-mongodb.{{ .Values.global.namespaceOverride | default .Release.Namespace }}.svc.cluster.local:27017/brewup-sales?authSource=admin'
            - name: BrewUp__MongoDbSettings__DatabaseName
              value: 'brewup-sales'
            - name: BrewUp__ServiceBusSettings__ConnectionString
              value: {{.Values.sales.serviceBus.connectionString }}
            - name: BrewUp__ServiceBusSettings__ClientId
              value: {{.Values.sales.serviceBus.clientId }}
          ports:
            - containerPort: {{ .Values.sales.port }}
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{.Values.sales.name }}
