apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaceOverride }}
  name: {{ .Values.sales.name }}
spec:
  selector:
    app: {{ .Values.sales.name }}
  ports:
    - port: {{.Values.sales.service.port }}
      targetPort: {{.Values.sales.port }}
  type: LoadBalancer